name: Nathaniel Navoa Portfolio
url: "https://github.com/nvnavoa" # The base hostname & protocol for your site

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0

# SEO and appearance
title: "Nathaniel Navoa | Spatial Data Scientist"
description: "Explore my portfolio showcasing my expertise in spatial science, geodetic engineering, and remote sensing."

# Social Links
social_links:
  - name: email
    url: nvnavoa@up.edu.ph
    icon: fas fa-envelope
  - name: github
    url: https://github.com/nvnavoa
    icon: fab fa-github

# Plugins and features
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Theme customizations
display:
  posts_on_homepage: true
  featured_image: true
  author_profile: true

# Styling options
style:
  primary_color: "#0056b3" # A professional blue color
  secondary_color: "#ffffff" # Clean white
  background_color: "#f8f9fa" # Light gray background
