name: Nathaniel Navoa Portfolio
url: "https://github.com/nvnavoa" 

# Use GitHub Pages compatible theme
remote-theme: jekyll-theme-minimal 

# SEO and appearance
title: "Nathaniel Navoa | Spatial Data Scientist"
description: "Explore my portfolio showcasing my expertise in spatial science, geodetic engineering, and remote sensing."

# Social Links
social_links:
  - name: email
    url: nvnavoa@up.edu.ph
    icon: fas fa-envelope
  - name: github
    url: https://github.com/nvnavoa
    icon: fab fa-github

# Plugins and features
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Theme customizations
display:
  posts_on_homepage: true
  featured_image: true
  author_profile: true

# Styling options
style:
  primary_color: "#0056b3"
  secondary_color: "#ffffff"
  background_color: "#f8f9fa"
